In [17]:
from __future__ import division
import numpy as np
import pandas as pd
#import load_data
from sklearn.cross_validation import StratifiedKFold
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier, GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression

def logloss(attempt, actual, epsilon=1.0e-15):
    """Logloss, i.e. the score of the bioresponse competition.
    """
    attempt = np.clip(attempt, epsilon, 1.0-epsilon)
    return - np.mean(actual * np.log(attempt) + (1.0 - actual) * np.log(1.0 - attempt))

In [2]:
np.random.seed(0) # seed to shuffle the train set

n_folds = 10
verbose = True
shuffle = False

In [3]:
data_trn = pd.read_csv('new_train.csv', index_col=False)
data_tst = pd.read_csv('new_test.csv', index_col=False)
data_trn = data_trn.drop('Unnamed: 0', axis=1)
data_tst = data_tst.drop('Unnamed: 0', axis=1)
target = ['ACTION']
feature_columns_to_use = [column for column in data_trn.columns if column not in target]

In [4]:
feature_columns_to_use

['RESOURCE_enum',
 'MGR_ID_enum',
 'ROLE_ROLLUP_1_enum',
 'ROLE_ROLLUP_2_enum',
 'ROLE_DEPTNAME_enum',
 'ROLE_TITLE_enum',
 'ROLE_FAMILY_DESC_enum',
 'ROLE_FAMILY_enum',
 'ROLE_CODE_enum']

In [5]:
data_trn

RESOURCE_enum  MGR_ID_enum  ROLE_ROLLUP_1_enum  ROLE_ROLLUP_2_enum  \
0               3050         4440                  21                  65   
1                644          162                  21                  69   
2               2706         1679                  50                  58   
3               2615          931                  21                  69   
4               3616         1010                  15                  13   
5               4172         1685                  19                  18   
6               1329         2051                  21                  69   
7                756          615                  21                  22   
8               1842           67                  21                  74   
9               5481         3797                  33                  38   
10               194          392                  21                  74   
11               380         4551                   9                  35   
12              5771         3150                  54                  77   
13               194         3437                   3                  34   
14              6929         2210                  21                  69   
15               751         1092                  50                  58   
16              7385         2532                  21                  36   
17              2448         3853                  21                  76   
18              6673         1152                  21                  69   
19              1499          979                  21                  74   
20              2809          892                  21                  65   
21               405         4679                  21                  65   
22              6850           60                  21                  65   
23               100         4440                  21                  65   
24               194         1245                  21                  36   
25              3377         2837                  54                  77   
26              5256         1718                  21                  36   
27               836         1463                  49                  84   
28              5315         3140                  35                  40   
29              5617          620                  21                  65   
...              ...          ...                 ...                 ...   
32739            853         2811                  14                  12   
32740           3323          431                  21                  73   
32741            987         1053                  21                  59   
32742           4597          272                  21                  65   
32743           1878         3435                  21                  74   
32744           3507          931                  21                  69   
32745            230         2753                  21                  69   
32746           1412          330                  21                  67   
32747           1499          779                  21                  65   
32748           5926          281                  21                  21   
32749           5078          184                  21                  67   
32750           5194          439                  21                  67   
32751            576          723                  21                  59   
32752           2014         2468                  39                  45   
32753           1023         3616                  53                  64   
32754           4311         3989                  11                  49   
32755           3506         3664                  21                  36   
32756           5783          436                  96                 133   
32757            611          801                  21                  65   
32758           2061          937                  21                  67   
327

In [6]:
X = data_trn.as_matrix(feature_columns_to_use)
y = data_trn.as_matrix(['ACTION']).ravel()

In [7]:
X_submission = data_tst.as_matrix(feature_columns_to_use)
y_id = data_tst.as_matrix(['id']).ravel()

#X, y, X_submission = load_data.load()

if shuffle:
    idx = np.random.permutation(y.size)
    X = X[idx]
    y = y[idx]

skf = list(StratifiedKFold(y, n_folds))

In [8]:
skf = list(StratifiedKFold(y, n_folds))

clfs = [RandomForestClassifier(n_estimators=100, n_jobs=-1, criterion='gini'),
        RandomForestClassifier(n_estimators=100, n_jobs=-1, criterion='entropy'),
        ExtraTreesClassifier(n_estimators=100, n_jobs=-1, criterion='gini'),
        ExtraTreesClassifier(n_estimators=100, n_jobs=-1, criterion='entropy'),
        GradientBoostingClassifier(learning_rate=0.05, subsample=0.5, max_depth=6, n_estimators=50)]

In [9]:
skf

[(array([ 3076,  3102,  3108, ..., 32766, 32767, 32768]),
  array([   0,    1,    2, ..., 3289, 3290, 3291])),
 (array([    0,     1,     2, ..., 32766, 32767, 32768]),
  array([3076, 3102, 3108, ..., 6560, 6561, 6562])),
 (array([    0,     1,     2, ..., 32766, 32767, 32768]),
  array([ 6474,  6487,  6504, ...,  9964,  9975, 10007])),
 (array([    0,     1,     2, ..., 32766, 32767, 32768]),
  array([ 9824,  9825,  9826, ..., 13107, 13108, 13116])),
 (array([    0,     1,     2, ..., 32766, 32767, 32768]),
  array([13109, 13110, 13111, ..., 16392, 16393, 16394])),
 (array([    0,     1,     2, ..., 32766, 32767, 32768]),
  array([16251, 16283, 16287, ..., 19978, 20001, 20007])),
 (array([    0,     1,     2, ..., 32766, 32767, 32768]),
  array([19650, 19651, 19652, ..., 23246, 23283, 23287])),
 (array([    0,     1,     2, ..., 32766, 32767, 32768]),
  array([22910, 22911, 22912, ..., 26333, 26342, 26345])),
 (array([    0,     1,     2, ..., 32766, 32767, 32768]),
  array([26201, 26

In [10]:
print "Creating train and test sets for blending."

dataset_blend_train = np.zeros((X.shape[0], len(clfs)))
dataset_blend_test = np.zeros((X_submission.shape[0], len(clfs)))

Creating train and test sets for blending.


In [11]:
for j, clf in enumerate(clfs):
    print j, clf
    dataset_blend_test_j = np.zeros((X_submission.shape[0], len(skf)))
    for i, (train, test) in enumerate(skf):
        print "Fold", i
        X_train = X[train]
        y_train = y[train]
        X_test = X[test]
        y_test = y[test]
        clf.fit(X_train, y_train)
        y_submission = clf.predict_proba(X_test)[:,1]
        dataset_blend_train[test, j] = y_submission
        dataset_blend_test_j[:, i] = clf.predict_proba(X_submission)[:,1]
    dataset_blend_test[:,j] = dataset_blend_test_j.mean(1)
print "Blending."

0 RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=-1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)
Fold 0
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Fold 6
Fold 7
Fold 8
Fold 9
1 RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=-1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)
Fold 0
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Fold 6
Fold 7
Fold 8
Fold 9
2 ExtraTreesClassifier(bootstrap=False, class_weight=None, criterion='gini',
           max_depth=None, max_features='auto', max_leaf_n

In [12]:
pd.DataFrame(X_train)

0     1    2    3    4    5     6   7    8
0      3050  4440   21   65  319    4     7  65    4
1       644   162   21   69  310   34    62  67   38
2      2706  1679   50   58   14    0  2590   3    0
3      2615   931   21   69  184   22  2357  65   23
4      3616  1010   15   13  160   70   380   4   77
5      4172  1685   19   18   23   36    68   3   40
6      1329  2051   21   69  320   60  2813   8   66
7       756   615   21   22  119  224  2605  21  234
8      1842    67   21   74  229  240  2823   1  251
9      5481  3797   33   38   13    0  2836   3    0
10      194   392   21   74   66   47     7  65   51
11      380  4551    9   35  145   65  1027  30   72
12     5771  3150   54   77  297  124   329  28  133
13      194  3437    3   34   33   88  1709   7   96
14     6929  2210   21   69   71   22     7  65   23
15      751  1092   50   58   35    1     3   5    1
16     7385  2532   21   36  164   22     7  65   23
17     2448  3853   21   76   95   41    75  24   45
18     6673  1152   21   69  310   19   827  65   20
19     1499   979   21   74  281   22     7  65   23
20     2809   892   21   65   63   92  2832  14  100
21      405  4679   21   65  103    4  2357  65    4
22     6850    60   21   65  140   46  2676  67   50
23      100  4440   21   65  220   22     7  65   23
24      194  1245   21   36  115   17     7  65   18
25     3377  2837   54   77  309   17   626  65   18
26     5256  1718   21   36  182    4     7  65    4
27      836  1463   49   84  112  328   598   5    6
28     5315  3140   35   40   14   36  1655   3   40
29     5617   620   21   65  209  103  1188  14  111
...     ...   ...  ...  ...  ...  ...   ...  ..  ...
29463  6846   726   21   21   46    4     7  65    4
29464  6803  3638   11   49   18   36  1406   3   40
29465   647  3249   21   65   88   27  1140  14   28
29466   227   941   11  118   53   22     7  65   23
29467   279     4   21   74  178   47     7  65   51
29468   194  1048   21   59  226  273   853   7  283
29469  5065   581   21   21   46   11     7   5   11
29470  2929   719   21   69  183   67  2493  16   74
29471    57   158   21   65   13   26  2608  13   27
29472  2943   500   21   65   88   52  1711  14   56
29473   879  3967   21   67  264  201  2853  22  211
29474   679   156   21   74  263   22     7  65   23
29475   165  4813   21   65   88   11   174   5   11
29476  6691   897   99  141  277  204  1777  14  214
29477  5566  1902   21   76  210   23   548  11   25
29478  4135   396   21   36   27   37  2206  21   41
29479  4923  4615   19   18   19    3  2739   3    3
29480  5065  1412   21   36  182  158   607  26  167
29481  2434  3186    7    5   13   36     5   3   40
29482   890  3746   25   26   13    0     2   3    0
29483   277  4731   32    0  258  328  1068   5    6
29484  1159   191   21   67  227    4     7  65    4
29485  7443   505   21   74  217   46  2676  67   50
29486  2296  1304   21   67   72    9    78  64    9
29487  1452   645   21   69  125   22     7  65   23
29488  2846  4065   24   25   14    1     8   5    1
29489  4403  4454   74   97  106   70   217   4   77
29490  2675  4166   63   83   20    6    10  66    5
29491   194  1323   21   73  100   21  1709   7   22
29492  2132  2542  129  109   65  354  1012  17  293

[29493 rows x 9 columns]

In [13]:
clf = LogisticRegression()
clf.fit(dataset_blend_train, y)
y_submission = clf.predict_proba(dataset_blend_test)[:,1]

print "Linear stretch of predictions to [0,1]"
y_submission = (y_submission - y_submission.min()) / (y_submission.max() - y_submission.min())
y_id=range(1,58922)
print "Saving Results."
#np.savetxt(fname='test.csv', X=y_submission, fmt='%0.9f')

Linear stretch of predictions to [0,1]
Saving Results.


In [14]:
# np.savetxt(fname='test.csv', X=zip(y_id,y_submission), fmt='%0.9f')

In [15]:
def fn_WriteSubmission(_file_name, _y_predict, _y_id):
    # Write Submission
    submission = pd.DataFrame({"ACTION": _y_predict}, index=_y_id)
    submission.index.name = 'Id'

    submission.to_csv(_file_name)
#Call
fn_WriteSubmission("blending.csv",y_submission,y_id)

In [16]:
y_id=range(1,58922)